remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Bilan(Elaine) Gao]
description: [I  am  an incoming reearch assistant in the department of Artificial intelliegnce at Chung-Ang University. My advoisor is YoungBin Kim, who leads the Intelligent Information Processing Lab(IIPL). I mainly work on conputer vision(CV). My research interests are: continual learning, representaion learning, knwoledge distillation.]
